version: '3.8'

services:
  be:
    image: d_preda_back_end
    build: ./BE
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: competition_bi
      # DATABASE_USERNAME: postgres
      # DATABASE_PASSWORD: root
      # DATABASE_IP: localhost
      # DATABASE_PORT: 5432
      # DATABASE_NAME: competition_bi
    ports:
      - "5432:5432"
